name: ppo_teacher
log_dir: ./runs_teacher
max_iterations: 50001
save_interval: 500
num_learning_epochs: 4
num_mini_batches: 4
gamma: 0.996
lam: 0.95
learning_rate: 0.0005
clip_param: 0.2
desired_kl: 0.01
shuffle_batch: false
init_std: 1.0
min_std: 0.2
policy_net:
- 128
- 128
value_net:
- 128
- 128
activation: lrelu
grasp_steps: 70
lift_steps: 30
reward_clip: -2.0
evaluation_enabled: false
evaluation_interval: 500
evaluation_rollouts: 1
